server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Spring Boot Application Logs
  - job_name: musinsa-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: musinsa-app
          __path__: /var/log/app/*.log
    pipeline_stages:
      - match:
          selector: '{job="musinsa-app"}'
          stages:
            - regex:
                expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(?P<thread>.*?)\] (?P<level>\w+)\s+(?P<logger>.*?) - (?P<message>.*)'
            - labels:
                thread:
                level:
                logger:
            - timestamp:
                source: timestamp
                format: '2006-01-02 15:04:05'
