spring:
  application:
    name: musinsa2
  
  # 공통 설정
  profiles:
    active: local  # 기본 프로파일
  
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  
  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

---
# 로컬 개발 환경
spring:
  config:
    activate:
      on-profile: local
  
  # SQL 초기화 설정 - 로컬에서만 실행
  sql:
    init:
      mode: embedded  # embedded DB에서만 실행
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      encoding: UTF-8
      separator: ;
      continue-on-error: false

---
# 운영 환경
spring:
  config:
    activate:
      on-profile: prod
  
  # 운영 환경에서는 SQL 초기화 비활성화
  sql:
    init:
      mode: never  # 운영에서는 데이터 초기화 안함
  
  # 운영 로깅 설정
logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    com.yl.musinsa2: INFO

---
# 테스트 환경
spring:
  config:
    activate:
      on-profile: test
  
  # 테스트용 SQL 초기화
  sql:
    init:
      mode: embedded
      data-locations: classpath:test-data.sql  # 테스트용 데이터
      encoding: UTF-8
